name: Deploy Test

on:
push:
branches-ignore:
- main

jobs:
deploy-test:
runs-on: ubuntu-latest
environment: test

steps:
  - name: Checkout Code
    uses: actions/checkout@v4

  - name: Verify SSH Connection
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ${{ secrets.EC2_USER }}
      key: ${{ secrets.EC2_SSH_KEY }}
      script: |
        echo "===== SERVER DETAILS ====="
        hostname
        whoami
        pwd

  - name: Check Active Slot
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ${{ secrets.EC2_USER }}
      key: ${{ secrets.EC2_SSH_KEY }}
      script: |
        cd /home/ubuntu/zomato-test

        ACTIVE_SLOT=$(cat active.txt 2>/dev/null || echo blue)

        echo "Current Active Slot: $ACTIVE_SLOT"

        if [ "$ACTIVE_SLOT" = "blue" ]; then
          echo "Next Slot: green"
        else
          echo "Next Slot: blue"
        fi

  - name: Pull Latest Code
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ${{ secrets.EC2_USER }}
      key: ${{ secrets.EC2_SSH_KEY }}
      script: |
        cd /home/ubuntu/zomato-test

        git fetch origin

        git reset --hard origin/${{ github.ref_name }}

        echo "===== CURRENT COMMIT ====="
        git rev-parse --short HEAD
